---
title: "Steps 11a and 11b"
author: "Andrew Willems and Tian Hong"
date: "6/6/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading needed packages, message=FALSE, echo=FALSE}
#Loading needed packages
library(BiocParallel)
library(data.table)
library(phateR)
library(SingleCellExperiment)
library(SummarizedExperiment)
library(svglite)
library(tidyverse)
```

```{r loading needed functions}
#Loading the needed functions from their respective files
source("cox_model.R")
source("model_optimizer.R")
```

## Step 11a: Getting ideal gene number for `MAD` metric on TCGA-COAD
```{r ideal gene number for mad on COAD}
mad.genes <- readRDS("mad_colon_and_rectal_cancer.rds")

#Getting ideal gene number for MAD metric on TCGA-COAD
gene_sizes <- seq(100, 3000, 50)
mad_cindices <- rep(0, length(gene_sizes))

for(gs in gene_sizes){
  cox_model <- cox_model_fitter(my.seed = 1,
                                cox.predictors = mad.genes,
                                cox.df = cox_df,
                                gene.num = gs,
                                tumor.stage = FALSE,
                                tumor.n = FALSE,
                                tumor.m = FALSE,
                                my.filename = paste0("mad_coad_coefs_",gs,"_genes.csv"))
  
  #Getting the top concordance index from the cross validation and then rounding
  #it to 4 digits to follow cv.glmnet reporting convention. Finally, we update
  #the mad_cindices list with the result
  top_cindex <- round(cox_model$CV$cvm[cox_model$CV$index[1]], digits = 4)
  mad_cindices[which(gene_sizes==gs)] <- top_cindex
  
}

#Binding the gene size and c-index vectors together to get the finished data
#frame
mad_cindices_coad_df <- as.data.frame(cbind(gene_sizes, mad_cindices))
mad_cindices_coad_df$method <- rep("MAD", nrow(mad_cindices_coad_df))
colnames(mad_cindices_coad_df)[2] <- "c_index"
```

Step 11b: Saving the data frame of the concordance index at various gene sizes for `MAD` metric on TCGA-COAD
```{r saving ideal gene number for mad on coad}
write.csv(mad_cindices_coad_df,
          "mad_cindices_coad_across_gene_size.csv")
```
